# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger: none

resources:
  repositories:
  - repository: finapsTemplates  # identifier (A-Z, a-z, 0-9, and underscore)
    type: git  # see below
    name: AzurePipelinesTemplates/AzurePipelinesTemplates  # repository name (format depends on `type`)

#The build has 4 seperate tasks run under 1 step
variables:
  DockerComposeFile: 'Database.FunctionalTests/docker-compose.yml'

jobs:
  - job: BuildBinaries
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: DotNetCore/build-test-project.yml@finapsTemplates
