trigger:
  branches:
    include:
      - master

# pr: none

resources:
  repositories:
  - repository: finapsTemplates  
    type: git  
    name: AzurePipelinesTemplates/AzurePipelinesTemplates  
    ref: refs/heads/feature/dotnet-templates

variables:
  - template: NuGet/release-variables.yml@finapsTemplates
  - name: Major
    value: 1
  - name: Minor
    value: 0
  - name: VersionPrefix
    value: $(Major).$(Minor).$(Patch)

jobs:
  - job: BuildAndTestProject
    displayName: Build and Test DotNet Project
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: NuGet/release-build.yml@finapsTemplates
